.PHONY: clean All

All:
	@echo "----------Building project:[ ProjectFranksCarpetChallenge - Debug ]----------"
	@cd "ProjectFranksCarpetChallenge" && "$(MAKE)" -f  "ProjectFranksCarpetChallenge.mk"
clean:
	@echo "----------Cleaning project:[ ProjectFranksCarpetChallenge - Debug ]----------"
	@cd "ProjectFranksCarpetChallenge" && "$(MAKE)" -f  "ProjectFranksCarpetChallenge.mk" clean
