.PHONY: clean All

All:
	@echo "----------Building project:[ DecrementForLoop - Debug ]----------"
	@cd "DecrementForLoop" && "$(MAKE)" -f  "DecrementForLoop.mk"
clean:
	@echo "----------Cleaning project:[ DecrementForLoop - Debug ]----------"
	@cd "DecrementForLoop" && "$(MAKE)" -f  "DecrementForLoop.mk" clean
