.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_4_Solution - Debug ]----------"
	@cd "C:\Users\amillikin\cpp\Section20\Challenge_4_Solution" && "$(MAKE)" -f  "Challenge_4_Solution.mk"
clean:
	@echo "----------Cleaning project:[ Challenge_4_Solution - Debug ]----------"
	@cd "C:\Users\amillikin\cpp\Section20\Challenge_4_Solution" && "$(MAKE)" -f  "Challenge_4_Solution.mk" clean
