.PHONY: clean All

All:
	@echo "----------Building project:[ myTemplate - Debug ]----------"
	@cd "myTemplate" && "$(MAKE)" -f  "myTemplate.mk"
clean:
	@echo "----------Cleaning project:[ myTemplate - Debug ]----------"
	@cd "myTemplate" && "$(MAKE)" -f  "myTemplate.mk" clean
