.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_4 - Debug ]----------"
	@cd "C:\Users\amillikin\cpp\Section19\Challenge_4" && "$(MAKE)" -f  "Challenge_4.mk"
clean:
	@echo "----------Cleaning project:[ Challenge_4 - Debug ]----------"
	@cd "C:\Users\amillikin\cpp\Section19\Challenge_4" && "$(MAKE)" -f  "Challenge_4.mk" clean
